const CONFIG = {
    introTitle: 'Minh Thư ơi',
    introDesc: `Tớ có điều này muốn nói`,
    btnIntro: 'hihi',
    title: 'Tớ thích cậu lâu lắm rồi 😙',
    desc: 'Có lẽ ngay từ lúc thấy nụ cười ấy Cậu cho tớ cơ hội nha ',
    btnYes: 'Tớ đồng ý',
    btnNo: 'Không, Đéo nhé !! :3',
    question:'Cậu không từ chối tớ như mọi khi nữa hả ♥️',
    btnReply: 'Cho tớ biết lí do nha',
    reply: 'Tớ cho cậu cơ hội đó !!',
    mess: ' Tớ sẽ trân trọng, yêu cậu nhiều',
    messDesc: 'Hết dịch tớ mời cậu đi ăn nhé 🥰',
    btnAccept: 'Okiiiii lun <3',
    messLink: 'http://fb.com' //link mess của các bạn. VD: https://m.me/nam.nodemy
